### ISSUE TITLE
XPA 2.1.15.lsst1 Failing on Install (Error 252)

### ISSUE THREAD

**Issue by JPGlaser** [lsst/xpa#1]
To Whom it May Concern,

I attempted to install the lsst-app and lsst-sim packages today. However, I seem to be consistently failing install at the xpa-2.1.14.lsst1 section. The error code can be found below:

```
***** error: from /home/user_name/lsst/EupsBuildDir/Linux64/xpa-2.1.15.lsst1/build.log:
xtloop.c:84: error: (Each undeclared identifier is reported only once
xtloop.c:84: error: for each function it appears in.)
xtloop.c:86: error: ‘xpa_app’ undeclared (first use in this function)
xtloop.c:87: error: ‘struct xpaxtrec’ has no member named ‘id’
xtloop.c:88: error: ‘XtPointer’ undeclared (first use in this function)
xtloop.c:88: error: expected ‘)’ before ‘XtInputReadMask’
xtloop.c:93: error: ‘struct xpaxtrec’ has no member named ‘id’
xtloop.c:94: error: expected ‘)’ before ‘XtInputReadMask’
xtloop.c: In function ‘XPAXtDisableOneInput’:
xtloop.c:122: error: ‘struct xpaxtrec’ has no member named ‘id’
xtloop.c:122: error: ‘XtInputId’ undeclared (first use in this function)
xtloop.c:124: error: ‘struct xpaxtrec’ has no member named ‘id’
xtloop.c:125: error: ‘struct xpaxtrec’ has no member named ‘id’
xtloop.c: In function ‘XPAXtAddInput’:
xtloop.c:218: error: ‘xpa_app’ undeclared (first use in this function)
xtloop.c:219: error: ‘XtAppContext’ undeclared (first use in this function)
xtloop.c:219: error: expected ‘;’ before ‘app’
make: *** [xtloop.o] Error 1
make: *** Waiting for unfinished jobs....
+ exit -4
eups distrib: Failed to build xpa-2.1.15.lsst1.eupspkg: Command:
    source /home/user_name/lsst/eups/bin/setups.sh; export EUPS_PATH=/home/user_name/lsst; (/home/user_name/lsst/EupsBuildDir/Linux64/xpa-2.1.15.lsst1/build.sh) >> /home/user_name/lsst/EupsBuildDir/Linux64/xpa-2.1.15.lsst1/build.log 2>&1 4>/home/user_name/lsst/EupsBuildDir/Linux64/xpa-2.1.15.lsst1/build.msg 
exited with code 252 
```

Any ideas on a solution to this would be helpful. I can provide additional information as needed. Thanks in advance.

Warm Regards,
Joseph Glaser

**Comment by PaulPrice** [comment]
Do you have a different version of xpa installed on your machine?

**Comment by JPGlaser** [comment]
Not to my knowledge. This is a completely fresh install on our department's cluster.

**Comment by PaulPrice** [comment]
Could you please upload the entire build log (/home/user_name/lsst/EupsBuildDir/Linux64/xpa-2.1.15.lsst1/build.log)?

**Comment by PaulPrice** [comment]
Is it possible your department has built xpa on its cluster?

**Comment by JPGlaser** [comment]
Its highly unlikely as this would be the first time anyone has installed the main bulk of the lsst framework that would require it, however I will discuss it with one of our collabs. In the meantime, I have uploaded the log here: http://textuploader.com/x6tu
Hope this helps a bit.

**Comment by PaulPrice** [comment]
The long lines all end in a `$`.  Is this the actual file, or a cut-and-paste of it?

**Comment by JPGlaser** [comment]
Cut and paste. Having a bit of a permission battle at the moment to pull the actual file off the server to my local machine for some reason.

**Comment by jdswinbank** [comment]
Even despite the copy & paste problem, I think the key issue is clear enough -- you need to track down `X11/Intrinsic.h`. Could be that it's just not installed on your cluster, or it might be that it's hidden in some non-obvious location.

See https://confluence.lsstcorp.org/display/LSWUG/Prerequisites for the prerequisites for the LSST stack -- the file you're looking for should be in `libXt-devel` on RHEL or `libxt-dev` on Ubuntu.

**Comment by PaulPrice** [comment]
Well spotted, @jdswinbank.

**Comment by JPGlaser** [comment]
Yeah, looks like libxt-dev is not running on the cluster. Now the question becomes if I should I attempt to install these packages locally, or see if I can get my system admin to install any of the prereqs universally. Does the eups installer know how to search for these packages when they are local installs?

PS: If you still need this @PaulPrice, the full file is here: http://textuploader.com/x6t3

**Comment by PaulPrice** [comment]
Installing it yourself is likely a huge pain.  If your admins won't install it on the system, they may be able to point you to a system where it is installed.

**Comment by JPGlaser** [comment]
Thanks for your help thus far @PaulPrice & @jdswinbank. I have an email out to the system admin, so hopefully we can get it resolved tomorrow. Will update here when I figure out if that works or not.

**Comment by RobertLuptonTheGood** [comment]
Is xpa the only place we require X11?  We use xpa in the afw image display code (it could be made optional, I suppose)

**Comment by JPGlaser** [comment]
Alright guys, it seems that after these packages were installed, the program compiles just fine on the cluster. Thanks for helping me identify exactly what was going wrong with it. As a side note, is it a necessity to use the -devel versions of the packages? 'Cause most of these are default installed for the non-devel versions.

**Comment by RobertLuptonTheGood** [comment]
The devel versions are usually needed to get the .h files.

You should always install -devel versions of everything.
